# Generated by Django 6.0.4 on 2026-05-27 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_video_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_upload_mb', models.PositiveIntegerField()),
                ('max_quality', models.CharField(default='1080p', max_length=10)),
                ('analytics_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CdnDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_location', models.CharField(max_length=10)),
                ('bytes_served', models.PositiveBigIntegerField(default=0)),
                ('cache_status', models.CharField(choices=[('HIT', 'Cache Hit'), ('MISS', 'Cache Miss'), ('BYPASS', 'Bypass'), ('EXPIRED', 'Expired')], default='HIT', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(default=206)),
                ('response_time_ms', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdn_logs', to='streaming.video')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streaming.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_pct', models.PositiveSmallIntegerField()),
                ('viewer_pct', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_points', to='streaming.video')),
            ],
            options={
                'ordering': ['position_pct'],
                'unique_together': {('video', 'position_pct')},
            },
        ),
        migrations.CreateModel(
            name='VideoRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('trending', 'Trending'), ('same_category', 'Same Category')], default='collaborative', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='streaming.video')),
                ('target_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='streaming.video')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('source_video', 'target_video')},
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('watch_duration_s', models.PositiveIntegerField(default=0)),
                ('completion_pct', models.FloatField(default=0.0)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('tv', 'Smart TV')], default='desktop', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('quality_watched', models.CharField(default='auto', max_length=10)),
                ('buffering_events', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_events', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_events', to='streaming.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', 'created_at'], name='streaming_w_video_i_564d2e_idx'), models.Index(fields=['user', 'created_at'], name='streaming_w_user_id_de254e_idx')],
            },
        ),
    ]
